[package]
name = "wgslx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
naga = { version = "0.14.1", features = ["validate", "wgsl-in", "wgsl-out", "span", "serde", "serialize", "clone", "arbitrary", "pp-rs", "compact", "deserialize"] }
tokio = { version = "1.34.0", features = ["full"] }
tower-lsp = "0.20.0"
