[package]
name = "wgslx"
version = "0.1.0"
edition = "2021"
resolver = "2"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "crates/wgslx-wgpu/naga"
]

[workspace.dependencies.naga]
path = "crates/wgslx-wgpu/naga"
version = "0.14.0"

[dependencies]
# naga = { path = "../wgslx-wgpu/naga",  features = ["wgsl-in", "wgsl-out", "clone"] }
naga = { workspace = true, features = ["wgsl-in", "wgsl-out", "clone", "spv-in", "spv-out", "glsl-in", "glsl-out"] }
tokio = { version = "1.34.0", features = ["full"] }
tower-lsp = "0.20.0"
