[package]
name = "wgslx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "crates/wgslx-wgpu/naga",
  "crates/wgslx-lsp", 
  "crates/wgslx-cli"
]
default-members = [
  "crates/wgslx-wgpu/naga",
  "crates/wgslx-lsp", 
  "crates/wgslx-cli"
]

[workspace.dependencies.naga]
path = "crates/wgslx-wgpu/naga"

[dependencies]
naga = { workspace = true, features = ["wgsl-in", "wgsl-out", "clone", "glsl-in", "glsl-out", "spv-in", "spv-out", "serialize", "deserialize"] }
